import React from 'react'

const Hero = () => {
  return (
    <div>
      <div className="flex justify-center text-6xl text-designColor">
        &#128679; UNDER CONSTRUCTION &#128679;
      </div> 
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>

        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
        .<br/>
    </div>
  )
}

export default Hero